version: '2'
services:
  isijobs-app:
    image: isijobs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://isijobs-postgresql:5432/isiJobs
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8090:8090
  isijobs-postgresql:
    extends:
      file: postgresql.yml
      service: isijobs-postgresql
